<a href="https://colab.research.google.com/github/adam-klimas/data-science-bootcamp/blob/main/01_numpy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [2]:
import numpy as np
np.__version__

'2.0.2'

In [ ]:
print(dir(np))

In [ ]:
help(np.array)

In [10]:
x = np.array([1, 3])
x

array([1, 3])

In [11]:
print(x)

[1 3]


In [12]:
type(x)

numpy.ndarray

In [13]:
x.ndim

1

In [14]:
x.shape

(2,)

In [15]:
x.size

2

In [16]:
x.dtype

dtype('int64')

In [19]:
y = np.array([1.2, 3.3, 5.1])
y

array([1.2, 3.3, 5.1])

In [20]:
y.shape

(3,)

In [21]:
y.size

3

In [22]:
y.dtype

dtype('float64')

In [30]:
z = np.array([[1, 2], [4, 2]])
z

array([[1, 2],
       [4, 2]])

In [25]:
z.size

4

In [26]:
z.shape

(2, 2)

In [31]:
z.dtype

dtype('int64')